<meta name="description" content="Portfolio holding UCT Coatings is an advanced materials company.">
<title>UCT Coatings</title>
<div id="content" class="6u important(collapse)">

<!-- Content -->
	
		<header>
        <h2>UCT Coatings, Inc.</h2>
        <p class="subtitle">1.0% of portfolio as of 9/30/22</p>
        </header>
        <p>UCT Coatings is a leader in the development of metal coatings that reduce friction and improve efficiency in mechanical systems. The company's proprietary nickel-boron (NiB) coating technology offers exceptional hardness, high lubricity, and outstanding surface uniformity and has been shown to dramatically improve the energy efficiency of moving parts.</p>
        <p>Friction and the heat generated by it are bad news for mechanical devices. UCT's proprietary coating technology is being used to improve efficiency, extend product life, and reduce mechanical problems in industries as varied as oil &amp; gas, lumber, marine, and small arms.</p>
        
        <h3>Recent News</h3>

        <p>In December 2021, UCT Coatings announced the sale of its ownership interest in International Knife and Saw, Inc. (IKS) for $6.1 million. UCT will continue to provide substantial plating services to IKS on an ongoing basis.</p>

</div> 
   
<div id="sidebar2" class="3u">
  <section>
      <p><a class="image featured"><img src="images/logos/portfolio/uct.png" /></a></p>
      <header><h2>Connect With UCT</h2></header>
      <p><a href="http://www.uctcoatings.com/" target="new">www.uctcoatings.com</a></p>
      <ul class="social">
          <li><a href="https://twitter.com/UCTCoatings" target="new"><img src="images/buttons/twitter.png" /></a></li>
      </ul>
  </section>
 <!---closing DIV in lay_companies--->
 
 
 
  <section>
      